A lot of optimizations for amigaos

diff --git a/crashedit/Makefile.win32 b/crashedit/Makefile.win32
--- a/crashedit/Makefile.win32
+++ b/crashedit/Makefile.win32
@@ -39,8 +39,10 @@ CC = gcc
 AR = ar
 
 # Compiler flags
-CFLAGS = -I$(HERE).. -I$(HERE) -I$(HERE)core -I$(HERE)components -I$(HERE)ui -Wall -Wextra -Wpedantic -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement -Wimplicit-function-declaration -Wno-unused-parameter -std=gnu89 -O2
-LFLAGS = 
+CFLAGS = -I$(HERE).. -I$(HERE) -I$(HERE)core -I$(HERE)components -I$(HERE)ui \
+         $(ZLIBINC) $(PNGINC) \
+         -Wall -Wextra -Wpedantic -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement -Wimplicit-function-declaration -Wno-unused-parameter -std=gnu89 -O2
+LFLAGS = -mwindows
 
 # Platform-specific defines
 CDEFS = -DPLATFORM_WIN32 -DNO_TYPEDEF_BOOL -D_WINDOWS
@@ -73,7 +75,8 @@ CORE_OBJS = $(OBJDIR)/portable.o $(OBJDIR)/msg_wrap.o $(OBJDIR)/msgbase.o \
             $(OBJDIR)/jam_wrap.o $(OBJDIR)/utf8.o $(OBJDIR)/charset.o \
             $(OBJDIR)/ftn.o $(OBJDIR)/msghdr.o $(OBJDIR)/wrapper_io.o \
             $(OBJDIR)/clipboard.o $(OBJDIR)/attach.o $(OBJDIR)/freq.o $(OBJDIR)/keys.o \
-            $(OBJDIR)/ansi.o $(OBJDIR)/ncursesw_win32.o $(OBJDIR)/search.o $(OBJDIR)/nodelist.o
+            $(OBJDIR)/ansi.o $(OBJDIR)/ncursesw_win32.o $(OBJDIR)/te_rastport_win32.o \
+            $(OBJDIR)/search.o $(OBJDIR)/nodelist.o
 COMP_OBJS = $(OBJDIR)/editor.o $(OBJDIR)/editor_helper.o $(OBJDIR)/reader.o $(OBJDIR)/areafile.o $(OBJDIR)/config.o
 UI_OBJS   = $(OBJDIR)/ui_app.o \
             $(OBJDIR)/ui_session.o $(OBJDIR)/ui_popup.o $(OBJDIR)/ui_arealist.o \
@@ -85,7 +88,12 @@ UI_OBJS   = $(OBJDIR)/ui_app.o \
             $(OBJDIR)/ui_aka.o $(OBJDIR)/ui_attr.o $(OBJDIR)/ui_files.o \
             $(OBJDIR)/ui_popup_attach.o $(OBJDIR)/ui_popup_freq.o $(OBJDIR)/ui_setup.o \
             $(OBJDIR)/ui_search.o $(OBJDIR)/ui_popup_nodelist.o $(OBJDIR)/ui_glyph_picker.o \
-            $(OBJDIR)/ui_spell.o $(OBJDIR)/ui_mouse.o
+            $(OBJDIR)/ui_mouse.o
+
+# Spell checker UI objects
+ifeq ($(USE_HUNSPELL),1)
+UI_OBJS += $(OBJDIR)/ui_spell.o
+endif
 
 # Hyphen and Thesaurus UI objects
 ifeq ($(USE_HYPHEN),1)
@@ -99,6 +107,7 @@ UI_OBJS += $(OBJDIR)/ui_translate.o
 ifeq ($(USE_STARDICT),1)
 UI_OBJS += $(OBJDIR)/ui_dict.o
 UI_OBJS += $(OBJDIR)/ui_dict_picker.o
+UI_OBJS += $(OBJDIR)/ui_dict_reverse.o
 endif
 endif
 
@@ -110,8 +119,7 @@ CDEFS    += -DHAVE_HUNSPELL -I$(SPELL_DIR)
 # On Linux/BSD, use external Hunspell library (needs spell/spell.c wrapper)
 ifneq ($(findstring win,$(ARCH)),)
 # Windows: use native spellchecker only
-SPELL_OBJS = $(OBJDIR)/spellchecker_utils.o \
-             $(OBJDIR)/spellchecker_htab.o \
+SPELL_OBJS = $(OBJDIR)/spellchecker_htab.o \
              $(OBJDIR)/spellchecker_affix.o \
              $(OBJDIR)/spellchecker_core.o \
              $(OBJDIR)/spellchecker_suggest.o \
@@ -120,8 +128,7 @@ SPELL_OBJS = $(OBJDIR)/spellchecker_utils.o \
              $(OBJDIR)/spellchecker_dict_scan.o
 else ifeq ($(PLATFORM),amiga)
 # Amiga: use native spellchecker only
-SPELL_OBJS = $(OBJDIR)/spellchecker_utils.o \
-             $(OBJDIR)/spellchecker_htab.o \
+SPELL_OBJS = $(OBJDIR)/spellchecker_htab.o \
              $(OBJDIR)/spellchecker_affix.o \
              $(OBJDIR)/spellchecker_core.o \
              $(OBJDIR)/spellchecker_suggest.o \
@@ -165,7 +172,57 @@ TRANSLATE_OBJS =
 TRANSLATE_LIB =
 endif
 
-ALL_OBJS = $(CORE_OBJS) $(COMP_OBJS) $(SPELL_OBJS) $(TRANSLATE_OBJS) $(OBJDIR)/spellchecker_utils.o
+ALL_OBJS = $(CORE_OBJS) $(COMP_OBJS) $(SPELL_OBJS) $(TRANSLATE_OBJS) $(OBJDIR)/spellchecker_utils.o \
+           $(FT_OBJS) $(ZLIB_OBJS) $(PNG_OBJS)
+
+# FreeType objects (built from bundled freetype/ tree)
+FTDIR = $(HERE)freetype
+FT_OBJS = \
+  $(OBJDIR)/ftbase.o       $(OBJDIR)/ftbbox.o       \
+  $(OBJDIR)/ftbitmap.o     $(OBJDIR)/ftdebug.o      \
+  $(OBJDIR)/ftgasp.o       $(OBJDIR)/ftglyph.o      \
+  $(OBJDIR)/ftinit.o       $(OBJDIR)/ftmm.o         \
+  $(OBJDIR)/ftpatent.o     $(OBJDIR)/ftstroke.o     \
+  $(OBJDIR)/ftsynth.o      $(OBJDIR)/ftsystem.o     \
+  $(OBJDIR)/fttype1.o      $(OBJDIR)/ftwinfnt.o     \
+  $(OBJDIR)/autofit.o      $(OBJDIR)/smooth.o       \
+  $(OBJDIR)/raster.o       $(OBJDIR)/truetype.o     \
+  $(OBJDIR)/cff.o          $(OBJDIR)/sfnt.o         \
+  $(OBJDIR)/psnames.o      $(OBJDIR)/pshinter.o     \
+  $(OBJDIR)/ftgzip.o       $(OBJDIR)/ftlzw.o        \
+  $(OBJDIR)/type1.o        $(OBJDIR)/type1cid.o     \
+  $(OBJDIR)/pfr.o          $(OBJDIR)/type42.o       \
+  $(OBJDIR)/winfnt.o       $(OBJDIR)/pcf.o          \
+  $(OBJDIR)/bdf.o          $(OBJDIR)/psaux.o        \
+  $(OBJDIR)/sdf.o          $(OBJDIR)/svg.o
+
+# zlib objects (bundled zlib/ tree, required by FreeType PNG support)
+ZLIBDIR = $(HERE)zlib
+ZLIB_OBJS = \
+  $(OBJDIR)/adler32.o    $(OBJDIR)/compress.o   $(OBJDIR)/crc32.o      \
+  $(OBJDIR)/deflate.o    $(OBJDIR)/infback.o    $(OBJDIR)/inffast.o    \
+  $(OBJDIR)/inflate.o    $(OBJDIR)/inftrees.o   $(OBJDIR)/trees.o      \
+  $(OBJDIR)/uncompr.o    $(OBJDIR)/zutil.o
+
+# libpng objects (bundled libpng/ tree, required by FreeType PNG color emoji)
+PNGDIR = $(HERE)libpng
+PNG_OBJS = \
+  $(OBJDIR)/png.o        $(OBJDIR)/pngerror.o   $(OBJDIR)/pngget.o     \
+  $(OBJDIR)/pngmem.o     $(OBJDIR)/pngpread.o   $(OBJDIR)/pngread.o    \
+  $(OBJDIR)/pngrio.o     $(OBJDIR)/pngrtran.o   $(OBJDIR)/pngrutil.o   \
+  $(OBJDIR)/pngset.o     $(OBJDIR)/pngtrans.o   $(OBJDIR)/pngwio.o     \
+  $(OBJDIR)/pngwrite.o   $(OBJDIR)/pngwtran.o   $(OBJDIR)/pngwutil.o
+
+# Include paths for bundled third-party trees
+FTINC = -I$(FTDIR)/include
+ZLIBINC = -I$(ZLIBDIR)
+PNGINC = -I$(PNGDIR)
+
+# FreeType/zlib/libpng configuration headers used by prep/unprep
+FTOOPTION = $(FTDIR)/include/freetype/config/ftoption.h
+BACKUP    = $(FTOOPTION).backup
+ZCONF     = $(ZLIBDIR)/zconf.h
+PNGLIBCONF = $(PNGDIR)/pnglibconf.h
 
 all: $(TARGET) crashedit
 
@@ -265,6 +322,8 @@ $(OBJDIR)/ui_dict.o: $(UIDIR)/ui_dict.c $(UIDIR)/ui_dict.h | $(OBJDIR)
 	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
 $(OBJDIR)/ui_dict_picker.o: $(UIDIR)/ui_dict_picker.c $(UIDIR)/ui_dict_picker.h | $(OBJDIR)
 	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/ui_dict_reverse.o: $(UIDIR)/ui_dict_reverse.c $(UIDIR)/ui_dict_reverse.h | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
 endif
 endif
 
@@ -316,6 +375,135 @@ $(OBJDIR)/ansi.o: $(COREDIR)/ansi.c $(COREDIR)/ansi.h $(COREDIR)/utf8.h | $(OBJD
 
 $(OBJDIR)/ncursesw_win32.o: $(HERE)ncursesw_win32.c $(HERE)ncursesw_win32.h | $(OBJDIR)
 	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+
+$(OBJDIR)/te_rastport_win32.o: $(HERE)te_rastport_win32.c $(HERE)te_rastport_win32.h | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(FTINC) -c $< -o $@
+
+# Bundled FreeType library
+$(OBJDIR)/ftbase.o: $(FTDIR)/src/base/ftbase.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftbbox.o: $(FTDIR)/src/base/ftbbox.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftbitmap.o: $(FTDIR)/src/base/ftbitmap.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftdebug.o: $(FTDIR)/src/base/ftdebug.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftgasp.o: $(FTDIR)/src/base/ftgasp.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftglyph.o: $(FTDIR)/src/base/ftglyph.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftinit.o: $(FTDIR)/src/base/ftinit.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftmm.o: $(FTDIR)/src/base/ftmm.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftpatent.o: $(FTDIR)/src/base/ftpatent.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftstroke.o: $(FTDIR)/src/base/ftstroke.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftsynth.o: $(FTDIR)/src/base/ftsynth.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftsystem.o: $(FTDIR)/src/base/ftsystem.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/fttype1.o: $(FTDIR)/src/base/fttype1.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftwinfnt.o: $(FTDIR)/src/base/ftwinfnt.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/autofit.o: $(FTDIR)/src/autofit/autofit.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/smooth.o: $(FTDIR)/src/smooth/smooth.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/raster.o: $(FTDIR)/src/raster/raster.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/truetype.o: $(FTDIR)/src/truetype/truetype.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/cff.o: $(FTDIR)/src/cff/cff.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/sfnt.o: $(FTDIR)/src/sfnt/sfnt.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/psnames.o: $(FTDIR)/src/psnames/psnames.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/pshinter.o: $(FTDIR)/src/pshinter/pshinter.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftgzip.o: $(FTDIR)/src/gzip/ftgzip.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/ftlzw.o: $(FTDIR)/src/lzw/ftlzw.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/type1.o: $(FTDIR)/src/type1/type1.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/type1cid.o: $(FTDIR)/src/cid/type1cid.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/pfr.o: $(FTDIR)/src/pfr/pfr.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/type42.o: $(FTDIR)/src/type42/type42.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/winfnt.o: $(FTDIR)/src/winfonts/winfnt.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/pcf.o: $(FTDIR)/src/pcf/pcf.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/bdf.o: $(FTDIR)/src/bdf/bdf.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/psaux.o: $(FTDIR)/src/psaux/psaux.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/sdf.o: $(FTDIR)/src/sdf/sdf.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+$(OBJDIR)/svg.o: $(FTDIR)/src/svg/svg.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -DFT2_BUILD_LIBRARY $(FTINC) -c $< -o $@
+
+# Bundled zlib (used by FreeType PNG support)
+$(OBJDIR)/adler32.o: $(ZLIBDIR)/adler32.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/compress.o: $(ZLIBDIR)/compress.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/crc32.o: $(ZLIBDIR)/crc32.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/deflate.o: $(ZLIBDIR)/deflate.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/infback.o: $(ZLIBDIR)/infback.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/inffast.o: $(ZLIBDIR)/inffast.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/inflate.o: $(ZLIBDIR)/inflate.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/inftrees.o: $(ZLIBDIR)/inftrees.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/trees.o: $(ZLIBDIR)/trees.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/uncompr.o: $(ZLIBDIR)/uncompr.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+$(OBJDIR)/zutil.o: $(ZLIBDIR)/zutil.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) -c $< -o $@
+
+# Bundled libpng (used by FreeType PNG color emoji)
+$(OBJDIR)/png.o: $(PNGDIR)/png.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngerror.o: $(PNGDIR)/pngerror.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngget.o: $(PNGDIR)/pngget.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngmem.o: $(PNGDIR)/pngmem.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngpread.o: $(PNGDIR)/pngpread.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngread.o: $(PNGDIR)/pngread.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngrio.o: $(PNGDIR)/pngrio.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngrtran.o: $(PNGDIR)/pngrtran.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngrutil.o: $(PNGDIR)/pngrutil.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngset.o: $(PNGDIR)/pngset.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngtrans.o: $(PNGDIR)/pngtrans.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngwio.o: $(PNGDIR)/pngwio.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngwrite.o: $(PNGDIR)/pngwrite.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngwtran.o: $(PNGDIR)/pngwtran.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
+$(OBJDIR)/pngwutil.o: $(PNGDIR)/pngwutil.c | $(OBJDIR)
+	$(CC) $(CFLAGS) $(CDEFS) $(ZLIBINC) -c $< -o $@
 
 # Component objects
 $(OBJDIR)/areafile.o: $(COMPDIR)/areafile.c $(COMPDIR)/areafile.h | $(OBJDIR)
@@ -415,12 +603,52 @@ crashedit: $(CRASHEDIT)
 
 $(CRASHEDIT): $(HERE)main_ui.c $(TARGET) $(UI_OBJS) $(JAMLIB)
 	$(CC) $(CFLAGS) $(LFLAGS) $(CDEFS) $(HERE)main_ui.c $(UI_OBJS) $(TARGET) $(JAMLIB) \
-	      -o $@ -lws2_32 -lkernel32 -luser32 -lgdi32 $(TRANSLATE_LIB)
+	      -o $@ -lws2_32 -lkernel32 -luser32 -lgdi32 -lmsimg32 $(TRANSLATE_LIB)
+
+# ====================================================================
+# prep target -- install upstream zlib/libpng config headers and patch
+# FreeType for Windows (PNG + system zlib for color emoji fonts)
+# ====================================================================
+prep:
+	@if grep -q "crashedit:" $(FTOOPTION); then \
+	    echo "ERROR: $(FTOOPTION) already patched. Run 'unprep' first"; \
+	    exit 1; \
+	fi
+	@if [ ! -f $(ZLIBDIR)/zconf.h.in ]; then \
+	    echo "ERROR: $(ZLIBDIR)/zconf.h.in not found -- is zlib present?"; \
+	    exit 1; \
+	fi
+	@if [ ! -f $(PNGDIR)/scripts/pnglibconf.h.prebuilt ]; then \
+	    echo "ERROR: $(PNGDIR)/scripts/pnglibconf.h.prebuilt not found -- is libpng present?"; \
+	    exit 1; \
+	fi
+	@echo ">>> Installing upstream zconf.h (from zlib/zconf.h.in)"
+	@cp $(ZLIBDIR)/zconf.h.in $(ZCONF)
+	@echo ">>> Installing upstream pnglibconf.h (from libpng/scripts/pnglibconf.h.prebuilt)"
+	@cp $(PNGDIR)/scripts/pnglibconf.h.prebuilt $(PNGLIBCONF)
+	@echo ">>> Installing Windows-native ftsystem.c / ftdebug.c"
+	@if [ -f $(FTDIR)/builds/windows/ftsystem.c ]; then \
+	    cp $(FTDIR)/builds/windows/ftsystem.c $(FTDIR)/src/base/ftsystem.c; \
+	    cp $(FTDIR)/builds/windows/ftdebug.c  $(FTDIR)/src/base/ftdebug.c; \
+	fi
+	@echo ">>> Patching $(FTOOPTION) (PNG + SYSTEM_ZLIB on, SVG off)"
+	@cp $(FTOOPTION) $(BACKUP)
+	@sed -i \
+	    -e 's|^/\* #define FT_CONFIG_OPTION_USE_PNG \*/$$|#define FT_CONFIG_OPTION_USE_PNG /* crashedit:win */|' \
+	    -e 's|^/\* #define FT_CONFIG_OPTION_SYSTEM_ZLIB \*/$$|#define FT_CONFIG_OPTION_SYSTEM_ZLIB /* crashedit:win */|' \
+	    -e 's|^#define FT_CONFIG_OPTION_SVG$$|/* #define FT_CONFIG_OPTION_SVG */ /* crashedit:win */|' \
+	    $(FTOOPTION)
+	@echo ">>> Prep complete (win)"
+
+unprep:
+	@if [ -f $(BACKUP) ]; then \
+	    mv $(BACKUP) $(FTOOPTION); \
+	    echo ">>> $(FTOOPTION) restored"; \
+	fi
+	@rm -f $(ZCONF) $(PNGLIBCONF)
+	@echo ">>> custom headers removed"
 
 clean:
 	rm -rf $(OBJDIR) $(TARGET) $(CRASHEDIT)
 
-.PHONY: all clean
-	rm -rf $(OBJDIR) $(TARGET) $(CRASHEDIT)
-
-.PHONY: all clean
+.PHONY: all clean prep unprep
